### ISSUE TITLE
v0.25 breaks generation of nested error variants in Kotlin bindings

### ISSUE THREAD

**Issue by Voronar** [mozilla/uniffi-rs#1828]
There is a problem when we use `[Error]` enum as a variant value for another `[Error]` one for example.

UDL code:
```
[Error]
interface Sub1Error {
    One(string error);
    Two(string error);
};

[Error]
interface Sub2Error {
    One(string error);
    Two(string error);
};

[Error]
interface RootError {
    Sub1(Sub1Error error);
    Sub2(Sub2Error error);
};
```

Rust code:
```rust
#[derive(Debug, thiserror::Error)]
pub enum RootError {
    #[error(transparent)]
    Sub1 {
        #[from]
        error: Sub1Error,
    },
    #[error(transparent)]
    Sub2 {
        #[from]
        error: Sub2Error,
    },
}

#[derive(Debug, thiserror::Error)]
pub enum Sub1Error {
    #[error("{error}")]
    One { error: String },
    #[error("{error}")]
    Two { error: String },
}

#[derive(Debug, thiserror::Error)]
pub enum Sub2Error {
    #[error("{error}")]
    One { error: String },
    #[error("{error}")]
    Two { error: String },
}
```

Error:
```
uniffi-rs/target/tmp/uniffi-example-traits-74e2e027c7e1d172/uniffi/traits/traits.kt:1004:22: error: unresolved reference: Sub1Error
        val `error`: Sub1Error
                     ^
uniffi-rs/target/tmp/uniffi-example-traits-74e2e027c7e1d172/uniffi/traits/traits.kt:1011:22: error: unresolved reference: Sub2Error
        val `error`: Sub2Error
```

The example above works with versions 0.23 and 0.24 and earlier I think, but beginning with this change (https://github.com/mozilla/uniffi-rs/commit/5e3dea51f17ae59a695a40e23479d57262968bb6#diff-522f0ef157bc0a32453bafd790a9058a35cbb8a721df58a9b51b1ec6b74db5caL456) or at least in version 0.25 it doesn't.

Similar to https://github.com/mozilla/uniffi-rs/issues/1020 and https://github.com/mozilla/uniffi-rs/issues/1062

**Comment by Voronar** [comment]
As a workaround we can add custom filter on https://github.com/mozilla/uniffi-rs/blob/main/uniffi_bindgen/src/bindings/kotlin/templates/EnumTemplate.kt#L40 variant field type name and rename it with https://github.com/mozilla/uniffi-rs/blob/main/uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs#L268.

**Comment by mhammond** [comment]
This turns out to be tricky to do in a non-hacky way - https://github.com/mhammond/uniffi-rs/tree/issue/1828-error-enum-rename demonstrates this problem and the "other" problem where an Enum which is *not* an error is used.

The best solution might turn out to be something like you did, but we'd probably need to insist *every* type with a trailing `Error` gets rewritten to `Exception` - eg, in my example, the fact `OtherError` is *not* declared as an error probably doesn't mean the name should stay as `OtherError` but should probably unconditionally be `OtherException`.

This would obviously break other scenarios where this was *not* done and *not* desired though.

WDYT?

**Comment by Voronar** [comment]
In your example we need more information about enum variant argument type in template filter, not just a string name. But even with `AsType` as filter argument type we don't have an attribute to distinguish the regular [Enum] enum from the [Error] one. For that purpose we could add 'is_error' flag to `Enum` type here https://github.com/mozilla/uniffi-rs/blob/main/uniffi_meta/src/types.rs#L94 for example.

**Comment by mhammond** [comment]
Given the code in my branch, I believe UniFFI would previously have generated:

```
sealed class CoverallRootException: Exception() {
    // Each variant is a nested class
    class Complex(val `error`: ComplexException) : CoverallRootException() {
        override val message
            get() = "error=${ `error` }"
    }
    
    class Sub(val `error`: CoverallSubException) : CoverallRootException() {
        override val message
            get() = "error=${ `error` }"
    }
    
    class Other(val `error`: OtherError) : CoverallRootException() {
        override val message
            get() = "error=${ `error` }"
    }
...
}
```

Note how we have types named `ComplexException`, `CoverallSubException` and `OtherError`.

> For that purpose we could add 'is_error' flag to Enum type here

I think we can already do that via `is_name_used_as_error()` but that too would leave us with the above - but I was wondering whether "fixing" uniffi to again have that inconsistency is actually the best thing to do, or whether `OtherError` should also be `OtherException` *even though it is not defined using `[Error]`*.

**Comment by Voronar** [comment]
Honestly I'm in favour of not renaming errors at all and just for a caution in documentation: "Don't name your error exactly as 'Error/Exception' because of a potential platform specific name collision!". And in the end it is better to preserve original error names in generated bindings just from a debugging point of view.

**Comment by mhammond** [comment]
For better or worse, I think never renaming exceptions would be too much of a breaking change for our consumers for us to consider. OTOH, I wonder if type aliases might be the best (or worst) of both worlds?

**Comment by Voronar** [comment]
Alias is just a workaround, not a solution. But customers are customers and they don't like inconveniences.
At least this restriction must be documented somewhere.
