### ISSUE TITLE
Callback interface method cannot return callback interface

### ISSUE THREAD

**Issue by bancek** [mozilla/uniffi-rs#1947]
In uniffi 25 a callback interface cannot return another callback interface. This used to work up to uniffi 24.3.

Guessing this was broken in #1766 by @bendk .

`test.udl`:

```
callback interface Stream {
  bytes read();
};

callback interface StreamProvider {
  Stream stream();
};

namespace test {
};
```

`lib.rs`:

```rs
use std::fmt::Debug;

pub trait Stream: Send + Sync + Debug {
    fn read(&self) -> Vec<u8>;
}

pub trait StreamProvider: Send + Sync + Debug {
    fn stream(&self) -> Box<dyn Stream>;
}

uniffi::include_scaffolding!("test");
```

Error:

```
    Checking uniffi-liftreturn-bug v0.1.0 (/Users/luka/uniffi-liftreturn-bug)
error[E0277]: the trait bound `Box<dyn Stream>: LiftReturn<UniFfiTag>` is not satisfied
   --> /Users/luka/uniffi-liftreturn-bug/target/debug/build/uniffi-liftreturn-bug-b39dd21c4e7a5173/out/test.uniffi.rs:124:69
    |
124 |         FOREIGN_CALLBACK_STREAMPROVIDER_INTERNALS.invoke_callback::<Box<dyn r#Stream>, crate::UniFfiTag>(self.handle, 1, args_rbuf)
    |                                                   ---------------   ^^^^^^^^^^^^^^^^^ the trait `LiftReturn<UniFfiTag>` is not implemented for `Box<dyn Stream>`
    |                                                   |
    |                                                   required by a bound introduced by this call
    |
    = help: the following other types implement trait `LiftReturn<UT>`:
              bool
              i8
              i16
              i32
              i64
              u8
              u16
              u32
            and 13 others
note: required by a bound in `ForeignCallbackInternals::invoke_callback`
   --> /Users/luka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uniffi_core-0.25.3/src/ffi/callbackinterface.rs:172:12
    |
170 |     pub fn invoke_callback<R, UniFfiTag>(&self, handle: u64, method: u32, args: RustBuffer) -> R
    |            --------------- required by a bound in this associated function
171 |     where
172 |         R: LiftReturn<UniFfiTag>,
    |            ^^^^^^^^^^^^^^^^^^^^^ required by this bound in `ForeignCallbackInternals::invoke_callback`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `uniffi-liftreturn-bug` (lib) due to previous error
```

**Comment by mhammond** [comment]
Fixed in 6f9d65a7f0f48da60f71fb1b17c0f42b548b1087

**Comment by bancek** [comment]
Thank you 😊
