### ISSUE TITLE
Syntax issues with the generated binding code in Swift

### ISSUE THREAD

**Issue by gezihuzi** [mozilla/uniffi-rs#2058]
I used the v0.27.0 `uniffi` to generate Swift binding code, and encountered some syntax issues.

UDL file section definition:

```udl
interface DeviceManager {
    [Throws=Error]
    constructor([ByRef] string database_url);
};
```

Syntax issues code:
```swift
public convenience init(databaseUrl: String) {
    let pointer = throws try rustCallWithError(FfiConverterTypeClipError.lift) {
        uniffi_device_kit_fn_constructor_devicemanager_new(
            FfiConverterString.lower(databaseUrl), $0
        )
    }
    self.init(unsafeFromRawPointer: pointer)
}
```

Expected generated code:
```swift
public convenience init(databaseUrl: String) throws {
    let pointer = try rustCallWithError(FfiConverterTypeClipError.lift) {
        uniffi_device_kit_fn_constructor_devicemanager_new(
            FfiConverterString.lower(databaseUrl), $0
        )
    }
    self.init(unsafeFromRawPointer: pointer)
}
```

**Comment by badboy** [comment]
I can easily reproduce that and a-s is hitting it too.

**Comment by badboy** [comment]
quick bisect shows that this broke in https://github.com/mozilla/uniffi-rs/pull/2048
cc @mhammond 

easy to reproduce with this patch:

```patch
--- fixtures/coverall/src/coverall.udl
+++ fixtures/coverall/src/coverall.udl
@@ -282,4 +282,9 @@ interface ISecond {
   boolean compare(IFirst? other);
 };

+interface DeviceManager {
+    [Throws=CoverallError]
+    constructor([ByRef] string database_url);
+};
+
 dictionary EmptyStruct {};
diff --git fixtures/coverall/src/lib.rs fixtures/coverall/src/lib.rs
index d7ba23856..79edd4fc1 100644
--- fixtures/coverall/src/lib.rs
+++ fixtures/coverall/src/lib.rs
@@ -584,4 +584,13 @@ impl ISecond {

 pub struct EmptyStruct;

+pub struct DeviceManager;
+
+impl DeviceManager {
+    pub fn new(url: &String) -> Result<DeviceManager, CoverallError> {
+        todo!()
+    }
+}
+
+
 uniffi::include_scaffolding!("coverall");
```

Running this:

```
UNIFFI_TESTS_DISABLE_EXTENSIONS=kts,py,rb cargo test -p uniffi-fixture-coverall
```

fails with:

```
src/uniffi-rs/target/tmp/uniffi-fixture-coverall-6e842bdd9758c583/coverall.swift:1057:19: error: expected initial value after '='
    let pointer = throws try rustCallWithError(FfiConverterTypeCoverallError.lift) {
                  ^
src/uniffi-rs/target/tmp/uniffi-fixture-coverall-6e842bdd9758c583/coverall.swift:1057:18: error: consecutive statements on a line must be separated by ';'
    let pointer = throws try rustCallWithError(FfiConverterTypeCoverallError.lift) {
                 ^
                 ;
src/uniffi-rs/target/tmp/uniffi-fixture-coverall-6e842bdd9758c583/coverall.swift:1057:19: error: expected expression
    let pointer = throws try rustCallWithError(FfiConverterTypeCoverallError.lift) {
                  ^
error: fatalError
test uniffi_foreign_language_testcase_test_coverall_swift ... FAILED
```

**Comment by CaioSym** [comment]
Are there plans for a 0.27.1 release? 27.0  is somewhat unusable with this issue.

**Comment by mhammond** [comment]
See #2062
